package com.superapp.app.features.settings

import androidx.activity.compose.BackHandler
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.superapp.app.core.settings.SettingsRepository

/**
 * FILE 11 - The Settings screen.
 *
 * It reads the tree from SettingsModel.kt and shows it level by level:
 *
 *   Settings
 *     Security  ->  App Lock | Node Lock | Biometrics
 *     Advanced  ->  Developer Mode  ->  System Overview | Debug Console | ...
 *
 * - Tap a row with an arrow to go deeper.
 * - The top bar shows the path (Settings > Security > ...). Tap any part
 *   of it to jump back to that level.
 * - The ← button, or the phone's back button, goes up one level.
 *   At the top level the phone's back button returns Home.
 *
 * You do NOT edit this file to add settings. Edit SettingsModel.kt.
 *
 * HOW TO CHANGE THE LOOK:
 *  - Row shape      : change RoundedCornerShape(16.dp) in NodeRow
 *  - Row border     : change the 0.25f alpha in NodeRow
 *  - Title size     : change 22.sp in Header
 */
@Composable
fun SettingsScreen(
    repository: SettingsRepository,
    modifier: Modifier = Modifier
) {
    // The ids of the nodes we are inside, below the root. Empty = top level.
    var path by remember { mutableStateOf(emptyList<String>()) }
    val chain = remember(path) { resolveChain(path) }
    val current = chain.last()

    // Goes up one level. When already at the top level this is disabled,
    // so the handler in MainActivity takes over and returns Home.
    BackHandler(enabled = path.isNotEmpty()) { path = path.dropLast(1) }

    Column(modifier = modifier.fillMaxSize()) {

        Header(
            title = "${current.emoji}  ${current.title}",
            showBack = path.isNotEmpty(),
            onBack = { path = path.dropLast(1) }
        )

        Breadcrumb(
            chain = chain,
            onJump = { index -> path = path.take(index) }
        )

        Spacer(Modifier.height(8.dp))

        Box(modifier = Modifier.weight(1f)) {
            val content = current.content
            when {
                current.children.isNotEmpty() -> NodeList(
                    node = current,
                    onOpen = { child -> path = path + child.id }
                )

                content != null -> Box(
                    modifier = Modifier
                        .fillMaxSize()
                        .verticalScroll(rememberScrollState())
                        .padding(16.dp)
                ) {
                    content(repository)
                }

                else -> ComingSoonPage(current)
            }
        }
    }
}

/** Walks down the tree and returns the nodes from the root to where we are. */
private fun resolveChain(path: List<String>): List<SettingsNode> {
    val chain = mutableListOf(settingsRoot)
    for (id in path) {
        val next = chain.last().children.firstOrNull { it.id == id } ?: break
        chain += next
    }
    return chain
}

@Composable
private fun Header(title: String, showBack: Boolean, onBack: () -> Unit) {
    val colors = MaterialTheme.colorScheme
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .padding(horizontal = 16.dp, vertical = 8.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        if (showBack) {
            Box(
                modifier = Modifier
                    .size(40.dp)
                    .clip(CircleShape)
                    .background(colors.surface)
                    .border(1.dp, colors.primary.copy(alpha = 0.6f), CircleShape)
                    .clickable(onClick = onBack),
                contentAlignment = Alignment.Center
            ) {
                Text(text = "←", color = colors.onSurface, fontSize = 18.sp)
            }
            Spacer(Modifier.width(12.dp))
        }
        Text(
            text = title,
            color = colors.onBackground,
            fontSize = 22.sp,
            fontWeight = FontWeight.Bold
        )
    }
}

/** Settings › Security › Advanced ... Tap a part to jump back to it. */
@Composable
private fun Breadcrumb(chain: List<SettingsNode>, onJump: (Int) -> Unit) {
    val colors = MaterialTheme.colorScheme
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .horizontalScroll(rememberScrollState())
            .padding(horizontal = 16.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        chain.forEachIndexed { index, node ->
            val isLast = index == chain.lastIndex
            if (index > 0) {
                Text(
                    text = "  ›  ",
                    color = colors.onBackground.copy(alpha = 0.5f),
                    fontSize = 14.sp
                )
            }
            Text(
                text = node.title,
                color = if (isLast) colors.primary else colors.onBackground.copy(alpha = 0.7f),
                fontWeight = if (isLast) FontWeight.Bold else FontWeight.Normal,
                fontSize = 14.sp,
                modifier = Modifier.clickable(enabled = !isLast) { onJump(index) }
            )
        }
    }
}

@Composable
private fun NodeList(node: SettingsNode, onOpen: (SettingsNode) -> Unit) {
    LazyColumn(
        contentPadding = PaddingValues(16.dp),
        verticalArrangement = Arrangement.spacedBy(10.dp)
    ) {
        items(node.children, key = { it.id }) { child ->
            NodeRow(child = child, onClick = { onOpen(child) })
        }
    }
}

@Composable
private fun NodeRow(child: SettingsNode, onClick: () -> Unit) {
    val colors = MaterialTheme.colorScheme
    val shape = RoundedCornerShape(16.dp)
    val comingSoon = child.children.isEmpty() && child.content == null

    Row(
        modifier = Modifier
            .fillMaxWidth()
            .clip(shape)
            .background(colors.surface)
            .border(1.dp, colors.primary.copy(alpha = 0.25f), shape)
            .clickable(onClick = onClick)
            .padding(16.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        Text(text = child.emoji, fontSize = 24.sp)
        Spacer(Modifier.width(14.dp))

        Column(modifier = Modifier.weight(1f)) {
            Text(
                text = child.title,
                color = colors.onSurface,
                fontWeight = FontWeight.SemiBold,
                fontSize = 16.sp
            )
            if (child.subtitle.isNotEmpty()) {
                Text(
                    text = child.subtitle,
                    color = colors.onSurface.copy(alpha = 0.65f),
                    fontSize = 12.sp
                )
            }
        }

        Spacer(Modifier.width(8.dp))

        if (comingSoon) {
            Box(
                modifier = Modifier
                    .clip(RoundedCornerShape(8.dp))
                    .background(colors.primary.copy(alpha = 0.15f))
                    .padding(horizontal = 8.dp, vertical = 4.dp)
            ) {
                Text(text = "Coming soon", color = colors.primary, fontSize = 11.sp)
            }
        } else {
            Text(text = "›", color = colors.primary, fontSize = 22.sp)
        }
    }
}

@Composable
private fun ComingSoonPage(node: SettingsNode) {
    val colors = MaterialTheme.colorScheme
    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(32.dp),
        verticalArrangement = Arrangement.Center,
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        Text(text = node.emoji, fontSize = 56.sp)
        Spacer(Modifier.height(12.dp))
        Text(
            text = "Coming soon",
            color = colors.primary,
            fontSize = 20.sp,
            fontWeight = FontWeight.Bold
        )
        val note = node.note
        if (note != null) {
            Spacer(Modifier.height(8.dp))
            Text(
                text = note,
                color = colors.onBackground.copy(alpha = 0.7f),
                textAlign = TextAlign.Center
            )
        }
    }
}
