package com.superapp.app.features.home

import androidx.compose.animation.core.LinearEasing
import androidx.compose.animation.core.animateFloat
import androidx.compose.animation.core.infiniteRepeatable
import androidx.compose.animation.core.rememberInfiniteTransition
import androidx.compose.animation.core.tween
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.gestures.detectDragGestures
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.BoxWithConstraints
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.offset
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.statusBarsPadding
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.State
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.key
import androidx.compose.runtime.mutableStateMapOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberUpdatedState
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.IntOffset
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.superapp.app.core.canvas.CanvasStore
import com.superapp.app.core.canvas.NodePosition
import com.superapp.app.core.feature.FeatureIcon
import com.superapp.app.core.feature.FeatureModule
import com.superapp.app.core.settings.FeatureStyle
import com.superapp.app.core.theme.LineStyle
import com.superapp.app.core.theme.LocalThemeSettings
import com.superapp.app.core.ui.FeatureCircle
import kotlin.math.cos
import kotlin.math.sin

/**
 * FILE 7 - The home screen: feature circles around a center, like your image.
 *
 * - Center circle: the app itself.
 * - Around it: one circle per feature, placed automatically in rings
 *   (up to 8 = one ring, more = two rings) unless the user dragged it
 *   to a custom spot.
 * - Thin lines connect every circle to the center.
 * - Search box at the top filters the circles by name.
 * - Gear button (top right) opens Settings.
 * - The top-left corner is left free for the SideMenuButton.
 *
 * Settings that change this screen:
 *  - Appearance > Glow / Connection Lines / Colors   (look)
 *  - Canvas > Visibility      : hide circles
 *  - Canvas > Node Layout     : circle size, center size, ring spread
 *  - Canvas > Drag & Drop     : move circles anywhere (edit mode)
 *
 * In edit mode every circle can be dragged, tapping does nothing, and a
 * bar at the bottom offers Reset and Done.
 *
 * You do NOT edit this file to add a feature. New features appear here
 * automatically once they are listed in AppFeatures.kt.
 *
 * HOW TO CHANGE THE LOOK:
 *  - Circle size     : change 76.dp (also scaled by the Settings circle size)
 *  - Center size     : change 96.dp
 *  - Ring spacing    : change the 0.85f / 0.75f (one ring) and 0.62f / 0.55f (inner ring)
 */
@Composable
fun HomeScreen(
    features: List<FeatureModule>,
    styles: Map<String, FeatureStyle>,
    onOpen: (String) -> Unit,
    onOpenSettings: () -> Unit,
    modifier: Modifier = Modifier
) {
    val context = LocalContext.current
    val settings = LocalThemeSettings.current
    val colors = MaterialTheme.colorScheme

    val canvasStore = remember { CanvasStore.get(context) }
    val canvas by canvasStore.state.collectAsState()

    var query by remember { mutableStateOf("") }

    val visible = remember(features, query, canvas.hidden) {
        val q = query.trim()
        features.filter { feature ->
            feature.id !in canvas.hidden &&
                (q.isEmpty() || feature.title.contains(q, ignoreCase = true))
        }
    }

    // Positions (in dp from the center) of circles that are being dragged right now.
    val liveOffsets = remember { mutableStateMapOf<String, Offset>() }
    LaunchedEffect(canvas.positions) { liveOffsets.clear() }

    Box(modifier = modifier.fillMaxSize()) {

        // ----- circles area (below the top row) -----
        Box(
            modifier = Modifier
                .fillMaxSize()
                .padding(top = 76.dp, bottom = 16.dp)
        ) {
            BoxWithConstraints(modifier = Modifier.fillMaxSize()) {
                val circleSize = 76.dp * settings.circleScale
                val centerSize = 96.dp * settings.circleScale * canvas.centerScale

                // Half-width and half-height of the area the ring can use (in dp).
                val rx = (maxWidth / 2 - circleSize / 2 - 6.dp).coerceAtLeast(40.dp).value
                val ry = (maxHeight / 2 - circleSize / 2 - 24.dp).coerceAtLeast(40.dp).value

                val autoPoints = remember(visible.size, rx, ry, canvas.ringSpread) {
                    layoutPoints(
                        count = visible.size,
                        rx = rx * canvas.ringSpread,
                        ry = ry * canvas.ringSpread
                    )
                }

                // Where a circle is right now, in dp from the center:
                // being dragged > saved custom spot > automatic ring.
                val positionOf: (String, Int) -> Offset = { id, index ->
                    liveOffsets[id]
                        ?: canvas.positions[id]?.let { Offset(it.x * rx, it.y * ry) }
                        ?: autoPoints.getOrNull(index)?.let { Offset(it.first, it.second) }
                        ?: Offset.Zero
                }
                val positionOfNow by rememberUpdatedState(positionOf)

                // Line look comes from Settings > Appearance > Connection Lines.
                val baseLineColor = settings.lineColor?.let { Color(it) } ?: colors.primary
                val lineColor = baseLineColor.copy(alpha = settings.lineAlpha.coerceIn(0f, 1f))
                val lineWidthDp = settings.lineWidth

                // PULSE style only: a value that loops from 0 to 1 again and again.
                // It is read while drawing, so only the lines redraw, not the screen.
                val pulsePhase: State<Float>? =
                    if (settings.lineStyle == LineStyle.PULSE) {
                        rememberInfiniteTransition(label = "linePulse").animateFloat(
                            initialValue = 0f,
                            targetValue = 1f,
                            animationSpec = infiniteRepeatable(tween(2400, easing = LinearEasing)),
                            label = "linePulseValue"
                        )
                    } else {
                        null
                    }

                // Lines from the center to every circle.
                Canvas(modifier = Modifier.fillMaxSize()) {
                    val c = Offset(size.width / 2f, size.height / 2f)
                    val stroke = lineWidthDp.dp.toPx()

                    visible.forEachIndexed { index, feature ->
                        val p = positionOf(feature.id, index)
                        val end = Offset(c.x + p.x.dp.toPx(), c.y + p.y.dp.toPx())

                        if (settings.lineStyle == LineStyle.CURVED) {
                            // Bend the line sideways with a control point off the middle.
                            val midX = (c.x + end.x) / 2f
                            val midY = (c.y + end.y) / 2f
                            val bendX = -(end.y - c.y) * 0.18f
                            val bendY = (end.x - c.x) * 0.18f
                            val path = Path().apply {
                                moveTo(c.x, c.y)
                                quadraticBezierTo(midX + bendX, midY + bendY, end.x, end.y)
                            }
                            drawPath(
                                path = path,
                                color = lineColor,
                                style = Stroke(width = stroke, cap = StrokeCap.Round)
                            )
                        } else {
                            drawLine(
                                color = lineColor,
                                start = c,
                                end = end,
                                strokeWidth = stroke,
                                cap = StrokeCap.Round
                            )
                        }

                        // A small light travelling along the line (PULSE only).
                        val phase = pulsePhase?.value
                        if (phase != null) {
                            val t = (phase + index * 0.17f) % 1f
                            drawCircle(
                                color = baseLineColor.copy(alpha = 0.9f),
                                radius = stroke * 2.2f,
                                center = Offset(c.x + (end.x - c.x) * t, c.y + (end.y - c.y) * t)
                            )
                        }
                    }
                }

                // Feature circles. The +11 moves the label out of the way so the
                // circle itself sits exactly on its line.
                visible.forEachIndexed { index, feature ->
                    key(feature.id) {
                        val indexNow by rememberUpdatedState(index)
                        val style = styles[feature.id]

                        FeatureCircle(
                            title = feature.title,
                            icon = style?.iconPath?.let { FeatureIcon.Custom(it) } ?: feature.icon,
                            accent = style?.accent?.let { Color(it) } ?: feature.defaultAccent,
                            diameter = circleSize,
                            onClick = { if (!canvas.editing) onOpen(feature.id) },
                            modifier = Modifier
                                .align(Alignment.Center)
                                .offset {
                                    val p = positionOf(feature.id, index)
                                    IntOffset(p.x.dp.roundToPx(), (p.y + 11f).dp.roundToPx())
                                }
                                .pointerInput(canvas.editing, feature.id, rx, ry) {
                                    if (canvas.editing) {
                                        // Save the final spot (as a fraction of the area).
                                        val commit: () -> Unit = {
                                            val p = liveOffsets[feature.id]
                                            if (p != null) {
                                                val nx = (p.x / rx).coerceIn(-1.1f, 1.1f)
                                                val ny = (p.y / ry).coerceIn(-1.1f, 1.1f)
                                                liveOffsets[feature.id] = Offset(nx * rx, ny * ry)
                                                canvasStore.update {
                                                    it.copy(
                                                        positions = it.positions +
                                                            (feature.id to NodePosition(nx, ny))
                                                    )
                                                }
                                            }
                                        }

                                        detectDragGestures(
                                            onDragStart = {
                                                liveOffsets[feature.id] =
                                                    positionOfNow(feature.id, indexNow)
                                            },
                                            onDragEnd = { commit() },
                                            onDragCancel = { commit() },
                                            onDrag = { change, dragAmount ->
                                                change.consume()
                                                val current = liveOffsets[feature.id]
                                                    ?: positionOfNow(feature.id, indexNow)
                                                liveOffsets[feature.id] = Offset(
                                                    current.x + dragAmount.x / density,
                                                    current.y + dragAmount.y / density
                                                )
                                            }
                                        )
                                    }
                                }
                        )
                    }
                }

                // Center circle.
                FeatureCircle(
                    title = "Super App",
                    icon = FeatureIcon.Emoji("✦"),
                    accent = colors.primary,
                    diameter = centerSize,
                    onClick = {},
                    modifier = Modifier
                        .align(Alignment.Center)
                        .offset(y = 11.dp)
                )

                if (visible.isEmpty()) {
                    Text(
                        text = if (query.isBlank()) {
                            "All circles are hidden.\nShow them in Settings > Canvas > Visibility."
                        } else {
                            "No feature found"
                        },
                        color = colors.onBackground.copy(alpha = 0.6f),
                        modifier = Modifier
                            .align(Alignment.Center)
                            .offset(y = 90.dp)
                    )
                }
            }
        }

        // ----- top row: search (center) and settings gear (right) -----
        OutlinedTextField(
            value = query,
            onValueChange = { query = it },
            placeholder = { Text("Search") },
            singleLine = true,
            shape = RoundedCornerShape(16.dp),
            modifier = Modifier
                .align(Alignment.TopCenter)
                .statusBarsPadding()
                .padding(top = 4.dp)
                .fillMaxWidth(0.55f)
        )

        Box(
            modifier = Modifier
                .align(Alignment.TopEnd)
                .statusBarsPadding()
                .padding(top = 8.dp, end = 12.dp)
                .size(44.dp)
                .clip(CircleShape)
                .background(colors.surface)
                .border(1.dp, colors.primary.copy(alpha = 0.6f), CircleShape)
                .clickable(onClick = onOpenSettings),
            contentAlignment = Alignment.Center
        ) {
            Text(text = "⚙️", fontSize = 20.sp)
        }

        // ----- edit mode bar -----
        if (canvas.editing) {
            val barShape = RoundedCornerShape(20.dp)
            Row(
                modifier = Modifier
                    .align(Alignment.BottomCenter)
                    .padding(bottom = 16.dp)
                    .clip(barShape)
                    .background(colors.surface)
                    .border(1.dp, colors.primary, barShape)
                    .padding(horizontal = 14.dp, vertical = 8.dp),
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                Text(
                    text = "Drag circles to move them",
                    color = colors.onSurface,
                    fontSize = 12.sp
                )
                TextButton(
                    onClick = { canvasStore.update { it.copy(positions = emptyMap()) } }
                ) {
                    Text("Reset")
                }
                Button(
                    onClick = { canvasStore.update { it.copy(editing = false) } }
                ) {
                    Text("Done")
                }
            }
        }
    }
}

/**
 * Works out where each circle goes, as (x, y) distances from the center in dp.
 * Circles are spread evenly on an ellipse, starting from the top.
 */
private fun layoutPoints(count: Int, rx: Float, ry: Float): List<Pair<Float, Float>> {
    if (count == 0) return emptyList()

    // 1 to 8 features: a single ring.
    if (count <= 8) {
        return ring(count, rx * 0.85f, ry * 0.75f, startDegrees = -90.0)
    }

    // More than 8: an inner ring and an outer ring.
    val innerCount = (count / 3).coerceAtLeast(3)
    val outerCount = count - innerCount
    return ring(innerCount, rx * 0.62f, ry * 0.55f, startDegrees = -90.0) +
        ring(outerCount, rx, ry, startDegrees = -72.0)
}

private fun ring(
    count: Int,
    rx: Float,
    ry: Float,
    startDegrees: Double
): List<Pair<Float, Float>> =
    List(count) { i ->
        val angle = Math.toRadians(startDegrees + 360.0 * i / count)
        Pair((rx * cos(angle)).toFloat(), (ry * sin(angle)).toFloat())
    }
