package com.superapp.app.features.settings

import androidx.activity.compose.BackHandler
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/**
 * SETTINGS FILE 2 - The Settings screen.
 *
 * It reads the menu from SettingsMenu.kt and shows it one level at a time:
 *
 *   Settings
 *     Security  ->  App Lock | Node Lock | Biometrics
 *     Advanced  ->  Developer Mode  ->  System Overview | Debug Console | ...
 *
 * - Tap a row with an arrow to go deeper.
 * - Tap the round back button, or the phone's back button, to go up one level.
 *   From the top level, the phone's back button returns to Home.
 * - A small line above the title shows where you are (Settings -> Advanced).
 *
 * You do NOT edit this file to add settings. Edit SettingsMenu.kt.
 *
 * HOW TO CHANGE THE LOOK:
 *  - Row roundness : 16.dp in NodeRow
 *  - Row spacing   : spacedBy(10.dp) in NodeList
 *  - Title size    : 22.sp in Header
 */
@Composable
fun SettingsScreen(
    env: SettingsEnv,
    modifier: Modifier = Modifier
) {
    // The ids of the rows we have opened, in order. Empty = top level.
    var path by remember { mutableStateOf(emptyList<String>()) }
    val trail = remember(path) { trailOf(path) }
    val current = trail.lastOrNull()

    // Phone back button: go up one level first. At the top level this
    // handler turns off and the app's own handler returns to Home.
    BackHandler(enabled = path.isNotEmpty()) {
        path = path.dropLast(1)
    }

    Column(
        modifier = modifier
            .fillMaxSize()
            .padding(horizontal = 16.dp)
    ) {
        Header(trail = trail, onUp = { path = path.dropLast(1) })
        Spacer(Modifier.height(12.dp))

        when {
            current == null ->
                NodeList(nodes = settingsTree) { path = path + it.id }

            current.children.isNotEmpty() ->
                NodeList(nodes = current.children) { path = path + it.id }

            else ->
                PageHost(node = current, env = env)
        }
    }
}

/** Turns a list of ids into the list of nodes it points to. */
private fun trailOf(path: List<String>): List<SettingsNode> {
    val result = mutableListOf<SettingsNode>()
    var level = settingsTree
    for (id in path) {
        val node = level.firstOrNull { it.id == id } ?: break
        result += node
        level = node.children
    }
    return result
}

@Composable
private fun Header(trail: List<SettingsNode>, onUp: () -> Unit) {
    val colors = MaterialTheme.colorScheme
    val title = trail.lastOrNull()?.let { "${it.emoji} ${it.title}" } ?: "⚙️ Settings"
    val breadcrumb = (listOf("Settings") + trail.dropLast(1).map { it.title })
        .joinToString("  →  ")

    Row(verticalAlignment = Alignment.CenterVertically) {
        if (trail.isNotEmpty()) {
            Box(
                modifier = Modifier
                    .size(40.dp)
                    .clip(CircleShape)
                    .background(colors.surface)
                    .border(1.dp, colors.primary.copy(alpha = 0.5f), CircleShape)
                    .clickable(onClick = onUp),
                contentAlignment = Alignment.Center
            ) {
                Text(text = "←", color = colors.onSurface, fontSize = 18.sp)
            }
            Spacer(Modifier.width(12.dp))
        }

        Column {
            if (trail.isNotEmpty()) {
                Text(
                    text = breadcrumb,
                    color = colors.onBackground.copy(alpha = 0.6f),
                    fontSize = 12.sp,
                    maxLines = 1,
                    overflow = TextOverflow.Ellipsis
                )
            }
            Text(
                text = title,
                color = colors.onBackground,
                fontSize = 22.sp,
                fontWeight = FontWeight.Bold
            )
        }
    }
}

@Composable
private fun NodeList(nodes: List<SettingsNode>, onOpen: (SettingsNode) -> Unit) {
    LazyColumn(
        verticalArrangement = Arrangement.spacedBy(10.dp),
        contentPadding = PaddingValues(bottom = 24.dp)
    ) {
        items(nodes, key = { it.id }) { node ->
            NodeRow(node = node, onClick = { onOpen(node) })
        }
    }
}

@Composable
private fun NodeRow(node: SettingsNode, onClick: () -> Unit) {
    val colors = MaterialTheme.colorScheme
    val shape = RoundedCornerShape(16.dp)
    val isBranch = node.children.isNotEmpty()
    val ready = isBranch || settingsPages.containsKey(node.id)

    Row(
        modifier = Modifier
            .fillMaxWidth()
            .clip(shape)
            .background(colors.surface)
            .border(1.dp, colors.primary.copy(alpha = 0.25f), shape)
            .clickable(onClick = onClick)
            .padding(horizontal = 16.dp, vertical = 14.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        Text(text = node.emoji, fontSize = 22.sp)
        Spacer(Modifier.width(14.dp))

        Column(modifier = Modifier.weight(1f)) {
            Text(
                text = node.title,
                color = colors.onSurface,
                fontSize = 16.sp,
                fontWeight = FontWeight.Medium
            )
            if (isBranch) {
                Text(
                    text = node.children.joinToString(", ") { it.title },
                    color = colors.onSurface.copy(alpha = 0.6f),
                    fontSize = 12.sp,
                    maxLines = 1,
                    overflow = TextOverflow.Ellipsis
                )
            }
        }

        if (!ready) {
            Text(text = "Coming soon", color = colors.primary, fontSize = 11.sp)
            Spacer(Modifier.width(8.dp))
        }
        Text(text = "›", color = colors.onSurface.copy(alpha = 0.5f), fontSize = 22.sp)
    }
}

/** Shows the real page if one is registered, otherwise the "Coming soon" page. */
@Composable
private fun PageHost(node: SettingsNode, env: SettingsEnv) {
    val page = settingsPages[node.id]
    if (page != null) {
        Box(modifier = Modifier.fillMaxSize()) { page(env) }
    } else {
        ComingSoonPage(node)
    }
}

@Composable
private fun ComingSoonPage(node: SettingsNode) {
    val colors = MaterialTheme.colorScheme
    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(24.dp),
        verticalArrangement = Arrangement.Center,
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        Text(text = node.emoji, fontSize = 48.sp)
        Spacer(Modifier.height(12.dp))
        Text(
            text = "Coming soon",
            color = colors.primary,
            fontSize = 22.sp,
            fontWeight = FontWeight.Bold
        )
        if (node.note.isNotEmpty()) {
            Spacer(Modifier.height(8.dp))
            Text(
                text = node.note,
                color = colors.onBackground.copy(alpha = 0.7f),
                textAlign = TextAlign.Center
            )
        }
    }
}
